import { FILTER_DATA, MODAL_CART_INFO, SORT_GEN } from './actions_types';
import image1 from '../assets/images/1.jpg';
import image2 from '../assets/images/2.jpeg';
import image3 from '../assets/images/3.jpg';
import image4 from '../assets/images/4.jpg';

const data = [
	{
		marca: 'BASSET',
		prenda: 'remera',
		id: '1',
		nombre: 'Remera BSC Negra',
		precio: 10000.0,
		descuento: 0,
		talles: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
		genero: 'hombre',
		images: [
			'https://d3ugyf2ht6aenh.cloudfront.net/stores/920/457/products/11421-fd6093fdf4a6aad61316766352702557-1024-1024.webp',
			'https://d3ugyf2ht6aenh.cloudfront.net/stores/920/457/products/11451-0d4435e62a0ff6036a16766352677646-1024-1024.webp',
			'https://d3ugyf2ht6aenh.cloudfront.net/stores/920/457/products/11341-923c6c4c5d8c65be8216766352678699-480-0.webp',
			'https://d3ugyf2ht6aenh.cloudfront.net/stores/920/457/products/11371-0198fabd0075e07d9f16766352685952-480-0.webp',
		],
	},
	{
		marca: 'BASSET',
		prenda: 'remera',
		id: '2',
		nombre: 'Remera Merch Logos Negra',
		precio: 9000.0,
		descuento: 0,
		talles: ['s', 'm', 'l', 'xl'],
		genero: 'hombre',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'BASSET',
		prenda: 'bermuda',
		id: '3',
		nombre: 'Bermuda 92',
		precio: 10000.0,
		descuento: 0,
		talles: ['m', 'l', 'xl', 'xxl'],
		genero: 'hombre',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'BASSET',
		prenda: 'remera',
		id: '4',
		nombre: 'Remera Alfon',
		precio: 10000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'hombre',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'BASSET',
		prenda: 'musculosa',
		id: '5',
		nombre: 'Musculosa Niza',
		precio: 9000.0,
		descuento: 0,
		talles: ['m', 'l', 'xl', 'xxl'],
		genero: 'hombre',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'BASSET',
		prenda: 'top',
		id: '6',
		nombre: 'Top Helena Rosada',
		precio: 9000.0,
		descuento: 0,
		talles: ['xs', 's', 'm', 'l', 'xl'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'BASSET',
		prenda: 'calza',
		id: '7',
		nombre: 'Biker Linda Rosada',
		precio: 9000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'BASSET',
		prenda: 'musculosa',
		id: '8',
		nombre: 'Musculosa Energy Negro',
		precio: 12000.0,
		descuento: 0,
		talles: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'BASSET',
		prenda: 'musculosa',
		id: '9',
		nombre: 'Musculosa Energy Blanca',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l', 'xl'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'BASSET',
		prenda: 'medias',
		id: '10',
		nombre: 'Medias',
		precio: 7000.0,
		descuento: 0,
		talles: ['m', 'l', 'xl', 'xxl'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'short',
		id: '101',
		nombre: 'Short Race',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'musculosa',
		id: '102',
		nombre: 'Musculosa Arya Rosa',
		precio: 6000.0,
		descuento: 0,
		talles: ['m', 'l', 'xl', 'xxl'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'musculosa',
		id: '103',
		nombre: 'Musculosa Arya Azul',
		precio: 6000.0,
		descuento: 0,
		talles: ['xs', 's', 'm', 'l', 'xl'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'campera',
		id: '104',
		nombre: 'Campera Nimbus Azul',
		precio: 20000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'campera',
		id: '105',
		nombre: 'Campera Nimbus Rosa',
		precio: 20000.0,
		descuento: 0,
		talles: ['xs', 's', 'm', 'l', 'xl', 'xxl'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'calza',
		id: '106',
		nombre: 'Calza Pescadora Treining Negra',
		precio: 13000.0,
		descuento: 0,
		talles: ['s', 'm', 'l', 'xl'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'calza',
		id: '107',
		nombre: 'Calza Pescadora Treining Negra',
		precio: 13000.0,
		descuento: 0,
		talles: ['m', 'l', 'xl', 'xxl'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'musculosa',
		id: '108',
		nombre: 'Musculosa Amarela',
		precio: 8500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'remera',
		id: '109',
		nombre: 'Remera Trend Blanca',
		precio: 8000.0,
		descuento: 0,
		talles: ['m', 'l', 'xl', 'xxl'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'remera',
		id: '110',
		nombre: 'Remera Trend Negra',
		precio: 8000.0,
		descuento: 0,
		talles: ['xs', 's', 'm', 'l', 'xl'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'calza',
		id: '111',
		nombre: 'Legging Boston',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'musculosa',
		id: '112',
		nombre: 'Musculosa Tiffany Blanco',
		precio: 8500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'musculosa',
		id: '113',
		nombre: 'Musculosa Tiffany Celeste',
		precio: 8500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'musculosa',
		id: '114',
		nombre: 'Musculosa Tiffany Coral',
		precio: 8500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'remera',
		id: '115',
		nombre: 'Remera Mich Negro',
		precio: 8000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'remera',
		id: '116',
		nombre: 'Remera Mich Gris',
		precio: 8000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'top',
		id: '117',
		nombre: 'Top Seamless Gris',
		precio: 11000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'calza',
		id: '118',
		nombre: 'Chupin Balanz',
		precio: 15000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'pollera',
		id: '119',
		nombre: 'Pollera Con Short Black',
		precio: 11000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'AGUA FITNESS',
		prenda: 'top',
		id: '120',
		nombre: 'Top Essential Rosado',
		precio: 11000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '201',
		nombre: 'University Black',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '202',
		nombre: 'Tiger Lila',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '203',
		nombre: 'Roar White',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '204',
		nombre: 'Element White',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '205',
		nombre: 'Aest Purple',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '206',
		nombre: 'University White',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '207',
		nombre: 'Raised Green',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '208',
		nombre: 'Worldwide Green',
		precio: 10000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '209',
		nombre: 'WorldWhite Black',
		precio: 10000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '210',
		nombre: 'NBD Black',
		precio: 10000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '211',
		nombre: 'Raisd White',
		precio: 10000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '212',
		nombre: 'Tiger Grey',
		precio: 12000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '213',
		nombre: 'New Skull',
		precio: 10000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '214',
		nombre: 'Musculosa Rustic University Pink',
		precio: 9000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '215',
		nombre: 'Musculosa Rustic Raisd Black',
		precio: 9000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '216',
		nombre: 'Short Alpha Pink',
		precio: 11000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '217',
		nombre: 'Short Alpha Black',
		precio: 11000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '218',
		nombre: 'Kit Woman Grey',
		precio: 15000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '219',
		nombre: 'Kit Woman Bordeaux',
		precio: 15000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'mujer',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'FUARK',
		prenda: 'musculosa',
		id: '220',
		nombre: 'Kit Texture Black',
		precio: 15000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'remera',
		id: '301',
		nombre: 'Remera Narok Francia Hombre',
		precio: 6500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'remera',
		id: '302',
		nombre: 'Remera Narok Marino Hombre',
		precio: 6500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'remera',
		id: '303',
		nombre: 'Remera Narok Negro Hombre',
		precio: 6500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'remera',
		id: '304',
		nombre: 'Remera Narok Verde Hombre',
		precio: 6500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'musculosa',
		id: '305',
		nombre: 'Musculosa Odisea B&W Mujer',
		precio: 4600.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'short',
		id: '306',
		nombre: 'Short Narok Negro',
		precio: 6000.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'short',
		id: '307',
		nombre: 'Short Calza Runing Fucsia',
		precio: 6500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'short',
		id: '308',
		nombre: 'Short Calza Runing Negro',
		precio: 6500.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'unisex',
		images: [image1, image2, image3, image4],
	},
	{
		marca: 'Yakka',
		prenda: 'calza',
		id: '309',
		nombre: 'Calza Deportiva Hombre',
		precio: 6400.0,
		descuento: 0,
		talles: ['s', 'm', 'l'],
		genero: 'hombre',
		images: [image1, image2, image3, image4],
	},
];

const initialState = {
	data: [...data],
	filteredData: [...data],
	name: '',
	size: '',
	quantity: 0,
	price: 0,
};

const reducer = (state = initialState, { type, payload }) => {
	switch (type) {
		case MODAL_CART_INFO:
			return {
				...state,
				name: payload.name,
				size: payload.selectedSize,
				quantity: payload.quantity,
				price: payload.price,
			};
		case FILTER_DATA:
			return {
				...state,
				filteredData: payload.filteredData,
			};
		case SORT_GEN: {
			const allowedGenders = [];
			if (payload.gender === 'male') {
				allowedGenders.push('hombre', 'unisex');
			} else if (payload.gender === 'female') {
				allowedGenders.push('mujer', 'unisex');
			} else allowedGenders.push('unisex');

			const genderData = data.filter((item) =>
				allowedGenders.includes(item.genero),
			);
			return {
				...state,
				filteredData: genderData,
			};
		}
		default:
			return { ...state };
	}
};

export default reducer;
